name: Create Release on v* tag pushed (no changelog)

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Echo tag output
      run: echo ${{ steps.get_version.outputs.version-without-v }}

    - name: Substitute version and download link in system.json
      uses: microsoft/variable-substitution@v1
      with:
        files: 'system.json'
      env:
        version: ${{steps.get_version.outputs.version-without-v}}
        download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.version}}/castle-falkenstein.zip

    - name: Create minimal system zip file
      run: zip -r ./castle-falkenstein.zip system.json template.json LICENSE src/ lang/ build/

    - name:  Create release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ steps.get_version.outputs.version }}
        tag: ${{ steps.get_version.outputs.version }}
        artifacts: './system.json, ./castle-falkenstein.zip'
        draft: false
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
