name: Release Creation

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # get part of the tag after the `v`
    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Echo tag output
      run: echo ${{ steps.get_version.outputs.version-without-v }}

    # Substitute the Manifest and Download URLs in the system.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'system.json'
      env:
        version: ${{steps.get_version.outputs.version-without-v}}
        download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.version}}/castle-falkenstein.zip

    # Create a zip file with all files required by the system to add to the release
    - run: zip -r ./castle-falkenstein.zip system.json template.json system/ lang/

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './system.json, ./castle-falkenstein.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}
